pull_request_rules:
  - name: automatic merge for main when CI passes
    conditions:
      - check-success=Test
      - author~=^dependabot(|-preview)\[bot\]$
      - base=master
    actions:
      merge:
        method: merge